### ISSUE TITLE
Webリポジトリのgit flow化

### ISSUE THREAD

**Issue by Hourier** [hengband/web#1]
リリースノートのレビューができるようにすることを見込む

権限的にHabuさんかdeskullさんしか実行できないと思われるので、お手数ですが対応お願いします

**Comment by habu1010** [comment]
とりあえずdevelopブランチを作って、変愚のリポジトリと同じく1人のレビュー必須にしておきました。

**Comment by sikabane-works** [comment]
ひとまずdevelopから生やして、都度修正要件ごとにブランチを切る体制こちらも意識するようになりましたので完了とさせていただければ。
