### ISSUE TITLE
アイテム選択時にクラッシュする件の潜在不具合可能性をリリースノートに明記する

### ISSUE THREAD

**Issue by Hourier** [hengband/web#9]
掲題の通り
[#137](https://github.com/hengband/hengband/pull/137) の修正は完全完了を確認できていないので、ユーザに周知することが目的

**Comment by sikabane-works** [comment]
了解今のリリースノートに追記します。

**Comment by sikabane-works** [comment]
https://hengband.osdn.jp/history/history3.0.0alpha6.html にて以下のようには書いたのでこの件は解決ということで。

> 以下のバグがまだ直っていないことを確認しています。ご了承下さい。
> アイテム選択時にクラッシュ (PullReq#137 参照)
