### ISSUE TITLE
楠瀬さんのサイトの新しいリンク先が見つかったので報告

### ISSUE THREAD

**Issue by KeitoTobi1** [hengband/web#90]
日本語版 EyAngband:http://ironhell.sakura.ne.jp/angband/eyangband/
日本語版 UnAngband:http://ironhell.sakura.ne.jp/angband/unangband/
日本語版 T.o.M.E.(旧名：PernAngband): http://ironhell.sakura.ne.jp/angband/tome/

どうやらミラーではないっぽい

**Comment by sikabane-works** [comment]
情報提供ありがとうございます、反映します。

**Comment by KeitoTobi1** [comment]
ありがとうございます。
